
spring:
  servlet:
    multipart:
      enabled: true
      location: /tmp
server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
graphql:
  servlet:
    actuator-metrics: true
    subscriptions:
      websocket:
        path: /graphql

graphql.playground:
  enabled: true
  cdn:
    enabled: false
  subscriptionEndpoint: /graphql